---
name: Login
description: Login into Azure Portal

inputs:
  creds:
    description: Azure credentions read from Azure Secrets
    required: true

runs:
  using: composite
  steps:
    - uses: Azure/login@v1.5.1
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: {{ inputs.creds }}
              